language: ruby

rvm:
  - 1.9.3
  - 2.1

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile

sudo: false

cache: bundler

before_script:
  - bundle exec rake setup

script:
  - bundle exec rake test_with_coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
